BoxLayout:
    orientation: 'vertical'
    BoxLayout:
        orientation: 'horizontal'
        TextInput:
            text: ''
            font_size: 20
        BoxLayout:
            orientation: 'vertical'
            Button:
                text: 'Up'
            Button:
                text: 'Down'
    Button:
        text: 'Convert m to km'
    Label:
        text: 'Label'
        font_size: 20
        color: (1, 1, 0, 1)